[package]
name = "labuf"
version = "0.1.3"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Tobias Hillemanns"]
repository = "https://github.com/Trombecher/lab"
categories = ["parsing", "data-structures", "compilers", "no-std"]

[dependencies]
fallible-iterator = "^0.3.0"
